CREATE TABLE IF NOT EXISTS lendingpad_loans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loan_id VARCHAR(100) UNIQUE,
  company_id VARCHAR(100),
  loan_number VARCHAR(50),
  lender_loan_number VARCHAR(100),
  broker_loan_number VARCHAR(100),
  loan_amount DECIMAL(15,2),
  total_loan_amount DECIMAL(15,2),
  purchase_price DECIMAL(15,2),
  appraisal_value DECIMAL(15,2),
  note_rate DECIMAL(6,3),
  apr DECIMAL(6,3),
  term INT,
  credit_score INT,
  units INT,
  ltv_ratio DECIMAL(6,3),
  combined_ltv DECIMAL(6,3),
  hc_ltv DECIMAL(6,3),
  front_dti DECIMAL(6,3),
  back_dti DECIMAL(6,3),
  pmi DECIMAL(10,2),
  other_financing DECIMAL(15,2),
  total_liquid_assets DECIMAL(15,2),
  total_liability_balance DECIMAL(15,2),
  total_liabilities_monthly DECIMAL(15,2),
  positive_net_rental_income DECIMAL(15,2),
  negative_net_rental_income DECIMAL(15,2),
  lender VARCHAR(255),
  broker VARCHAR(255),
  campaign VARCHAR(255),
  channel_type VARCHAR(100),
  document_type VARCHAR(100),
  agency_case_number VARCHAR(100),
  escrow_waiver TINYINT(1) DEFAULT 0,
  property_legal_description TEXT,
  legal_description_abbreviation VARCHAR(255),
  underwriter_comments TEXT,
  loan_reference_id VARCHAR(255),
  monday_item_id VARCHAR(50),
  monday_board_id VARCHAR(50),
  monday_synced_at TIMESTAMP NULL,
  raw_json JSON,
  received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_loan_number (loan_number),
  INDEX idx_loan_id (loan_id),
  INDEX idx_received_at (received_at),
  INDEX idx_monday_item_id (monday_item_id)
);
